services:
  web:
    build: .
    container_name: nuclear_web
    ports:
      - "${APP_PORT_WEB:-8082}:80"
    volumes:
      - .:/var/www/html
    # Aici îi spunem să ia TOATE variabilele din fișierul .env creat de noi
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: nginx:stable-alpine
    container_name: nuclear_frontend
    ports:
      - "${APP_PORT_FRONTEND:-8083}:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
    restart: unless-stopped

  composer:
    image: composer:lts
    container_name: nuclear_composer
    volumes:
      # Mapăm folderul curent în interiorul containerului la /app
      - .:/app
    # Când containerul pornește, va rula automat "composer install"
    command: install

# =======================================================
# BAZA DE DATE LOCALĂ ESTE DEZACTIVATĂ
# O poți lăsa așa comentată. Toate conexiunile se duc acum spre Neon!
# =======================================================
#  db:
#    image: postgres:15-alpine
#    container_name: nuclear_db
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - "${DB_PORT:-5432}:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#      - ./init-db/schema.sql:/docker-entrypoint-initdb.d/init.sql
#    restart: unless-stopped

#volumes:
#  pgdata: